base_url = "https://icp.administracionelectronica.gob.es"

dct_provincias = {
    "A Coruña": 15,
    "Albacete": 2,
    "Alicante": 3,
    "Almería": 4,
    "Araba": 1,
    "Asturias": 33,
    "Ávila": 5,
    "Badajoz": 6,
    "Barcelona": 8,
    "Bizkaia": 48,
    "Burgos": 9,
    "Cáceres": 10,
    "Cádiz": 11,
    "Cantabria": 39,
    "Castellón": 12,
    "Ceuta": 51,
    "Ciudad Real": 13,
    "Córdoba": 14,
    "Cuenca": 16,
    "Gipuzkoa": 20,
    "Girona": 17,
    "Granada": 18,
    "Guadalajara": 19,
    "Huelva": 21,
    "Huesca": 22,
    "Illes Balears": 7,
    "Jaén": 23,
    "La Rioja": 26,
    "Las Palmas": 35,
    "León": 24,
    "Lleida": 25,
    "Lugo": 27,
    "Madrid": 28,
    "Málaga": 29,
    "Melilla": 52,
    "Murcia": 30,
    "Navarra": 31,
    "Ourense": 32,
    "Palencia": 34,
    "Pontevedra": 36,
    "Salamanca": 37,
    "S.Cruz Tenerife": 38,
    "Segovia": 40,
    "Sevilla": 41,
    "Soria": 42,
    "Tarragona": 43,
    "Teruel": 44,
    "Toledo": 45,
    "Valencia": 46,
    "Valladolid": 47,
    "Zamora": 49,
    "Zaragoza": 50
}

dct_oficinas_madrid = offices = {
    "Cualquier oficina": 99,
    "CNP AVDA POBLADOS, Avda. de los Poblados, S/N, MADRID": 7,
    "CNP Comisaría de Alcalá de Henares, Avda. de Meco, s/n, ALCALÁ DE HENARES (Madrid)": 15,
    "CNP Comisaría de Alcobendas, Avda. de España, 52, ALCOBENDAS (Madrid)": 16,
    "CNP Comisaría de Alcorcón, Alfredo Nobel, 10, ALCORCÓN (Madrid)": 17,
    "CNP Comisaría de Aranjuez, Avda. Príncipe, 40, ARANJUEZ (Madrid)": 18,
    "CNP Comisaría de Arganda del Rey, Av.Mediterraneo(PoliciaLocal), 7, ARGANDA DEL REY (Madrid)": 27,
    "CNP Comisaría de Collado Villalba, SAN FERNANDO, 27, COLLADO VILLALBA (Madrid)": 28,
    "CNP Comisaría de Coslada, Guadalquivir, 16, COSLADA (Madrid)": 19,
    "CNP Comisaría de Fuenlabrada, Calle de los Ángeles, 9, FUENLABRADA (Madrid)": 20,
    "CNP Comisaría de Getafe, Churruca, 6, GETAFE (Madrid)": 21,
    "CNP Comisaría de Las Rozas de Madrid, José Echegaray, 22, Las Rozas de Madrid": 39,
    "CNP Comisaría de Leganés, Avda. de Universidad, 27, LEGANÉS (Madrid)": 22,
    "CNP Comisaría de Majadahonda, Ctra.Villanueva del Pardillo, 3, MAJADAHONDA (Madrid)": 29,
    "CNP Comisaría de Móstoles, Granada, 9, MÓSTOLES (Madrid)": 23,
    "CNP Comisaría de Parla, Avda. Juan Carlos I, 2, PARLA (Madrid)": 24,
    "CNP Comisaría de Pozuelo de Alarcón, Camino de las Huertas, 36, POZUELO DE ALARCÓN (Madrid)": 25,
    "CNP Comisaría de Rivas Vaciamadrid, José Hierro, 82, RIVAS-VACIAMADRID (Madrid)": 30,
    "CNP Comisaría de Torrejón de Ardoz, Hilados, 15, TORREJÓN DE ARDOZ (Madrid)": 26,
    "CNP Comisaría de Valdemoro, Avda. de España, 97, VALDEMORO (Madrid)": 31,
    "CNP OFICINA AQUILES 2, Aquiles, 2, MADRID": 34,
    "CNP Padre Piquer, Padre Piquer, 18, MADRID": 14,
    "CNP SAN FELIPE TIE, SAN FELIPE, 7, MADRID": 38,
    "CNP SANTA ENGRACIA, SANTA ENGRACIA, 18, MADRID": 36,
    "Comisaría de Getafe 2, churruca, 6, getafe": 35,
    "CREADE POZUELO, Paseo de la Casa Campo, 1, Pozuelo de Alarcón": 37,
    "Oficina de Asilo y Refugio, C/ Pradillo, 40, Madrid": 33
}

#user data
doc_type = ["PASAPORTE"]
nombre = ["JUAN PABLO CORREA"]
documento_id = ["YB1234567"]
ubicacion_usuario = [] #tentativo, tu incorporate later based on user preferences