base_url = "https://icp.administracionelectronica.gob.es/icpplus"

dct_provincias = {
    "A Coruña": 15,
    "Albacete": 2,
    "Alicante": 3,
    "Almería": 4,
    "Araba": 1,
    "Asturias": 33,
    "Ávila": 5,
    "Badajoz": 6,
    "Barcelona": 8,
    "Bizkaia": 48,
    "Burgos": 9,
    "Cáceres": 10,
    "Cádiz": 11,
    "Cantabria": 39,
    "Castellón": 12,
    "Ceuta": 51,
    "Ciudad Real": 13,
    "Córdoba": 14,
    "Cuenca": 16,
    "Gipuzkoa": 20,
    "Girona": 17,
    "Granada": 18,
    "Guadalajara": 19,
    "Huelva": 21,
    "Huesca": 22,
    "Illes Balears": 7,
    "Jaén": 23,
    "La Rioja": 26,
    "Las Palmas": 35,
    "León": 24,
    "Lleida": 25,
    "Lugo": 27,
    "Madrid": 28,
    "Málaga": 29,
    "Melilla": 52,
    "Murcia": 30,
    "Navarra": 31,
    "Ourense": 32,
    "Palencia": 34,
    "Pontevedra": 36,
    "Salamanca": 37,
    "S.Cruz Tenerife": 38,
    "Segovia": 40,
    "Sevilla": 41,
    "Soria": 42,
    "Tarragona": 43,
    "Teruel": 44,
    "Toledo": 45,
    "Valencia": 46,
    "Valladolid": 47,
    "Zamora": 49,
    "Zaragoza": 50
}

#user data
nombre = []
documento_id = []
ubicacion_usuario = [] #tentativo, tu incorporate later based on user preferences
